import {
  heroData,
  ctaData,
  footerData,
  navData,
  contactData,
  featureData,
  logoData,
  pricingData,
  projectData,
  serviceData,
  teamData,
  statisticData,
  itemData,
  cartItemData,
  filterItemData,
  orderPopupData,
  testimonialData,
  aboutData,
  galleryData,
  offerData,
  reservationData,
  menuData,
  chooseData
} from "./sectionsData";

const sectionDataMap = {
  'navbar': navData,
  'hero': heroData,
  'footer': footerData,
  'cta': ctaData,
  'contacts': contactData,
  'features': featureData,
  'logos': logoData,
  'pricing': pricingData,
  'projects': projectData,
  'services': serviceData,
  'team': teamData,
  'statistics': statisticData,
  'items': itemData,
  'cartItems': cartItemData,
  'filterItems': filterItemData,
  'orderPopups': orderPopupData,
  'testimonials': testimonialData,
  'about': aboutData,
  'gallery': galleryData,
  'offers': offerData,
  'reservations': reservationData,
  'menus': menuData,
  'chooses': chooseData
};

export const getSectionData = (section) => sectionDataMap[section] || [];